# Generated by Django 3.2.1 on 2021-05-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
